plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
    id 'maven-publish'
    id 'common'
}

def run = System.env.GITHUB_RUN_NUMBER
def isDev = System.env.DEV_BUILD == "true"

version = project.mod_version + (isDev ? "-dev.$run" : "") + "+mc.$minecraft_version"
group = project.maven_group
base.archivesName = project.archives_base_name

configurations.consumable("datagenElements")

dependencies {
    modApi include("com.kneelawk.graphlib:graphlib-core-fabric:$graphlib_version")
    //modLocalRuntime("com.kneelawk.graphlib:graphlib-debugrender-fabric:$graphlib_version")
    //modImplementation "vazkii.patchouli:Patchouli:$patchouli_version"

    modApi annotationProcessor(include("com.github.mattidragon:ConfigToolkit:$configtoolkit_version"))
    modApi include("dev.isxander:yet-another-config-lib:$yacl_version-fabric")
    modApi "com.terraformersmc:modmenu:$modmenu_version"
}

loom {
    // Apply datagen at runtime
    mods.register("extended_drawers") {
        sourceSet sourceSets.main
        sourceSet sourceSets.client
        modFiles.from file("src/main/generated")
    }
}

tasks.register("datagenJar", Jar) {
    from sourceSets.datagen.output
    archiveClassifier = "dev-datagen"
    destinationDirectory = layout.buildDirectory.dir("devlibs")
}

artifacts {
    datagenElements tasks.datagenJar
}