org.gradle.jvmargs=-Xmx1G

minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2

mod_version=4.3.0-beta.1
maven_group=io.github.mattidragon
archives_base_name=ExtendedDrawers

fabric_version=0.133.14+1.21.9
graphlib_version=2.0.3-beta.0.patbox.test+1.21.9
patchouli_version=1.20.1-81-FABRIC
yacl_version=3.8.0+1.21.9
modmenu_version=16.0.0-rc.1
configtoolkit_version=1.1.2
