[versions]
fabric-loom = "1.15-SNAPSHOT"
mod-publish-plugin = "1.1.0"
minecraft = "26.1"
fabric-loader = "0.18.4"
fabric-api = "0.144.0+26.1"
graphlib = "2.0.3-beta.0.matti+26.1"
patchouli = "1.20.1-81-FABRIC"
yacl = "3.9.1+26.1-fabric"
modmenu = "18.0.0-alpha.8"
configtoolkit = "1.1.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
graphlib-core = { module = "com.kneelawk.graphlib:graphlib-core-fabric", version.ref = "graphlib" }
graphlib-debugrender = { module = "com.kneelawk.graphlib:graphlib-debugrender-fabric", version.ref = "graphlib" }
configtoolkit = { module = "dev.mattidragon:ConfigToolkit", version.ref = "configtoolkit" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
patchouli = { module = "vazkii.patchouli:Patchouli", version.ref = "patchouli" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
mod-publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish-plugin" }